### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by jpuck** [davidgorges/color-contrast-php#1]
You're [currently requiring a development branch of a package][1].

For others to use `color-contrast-php` in their projects, they must declare a `dev` [minimum stability][2] because composer defaults to `stable`, otherwise they'll get a dependency resolution conflict during installation.

Alternatively, you could try to convince @mikeemoo to make a release tag for [ColorJizz-PHP][3] and require that as a stable version. Or fork it, make your own release, and then require that version.

[1]:https://github.com/davidgorges/color-contrast-php/blob/9c9edc9b1b75777cbe702eded0d7fef720ff98d4/composer.json#L10
[2]:https://getcomposer.org/doc/04-schema.md#minimum-stability
[3]:https://github.com/mikeemoo/ColorJizz-PHP

**Comment by davidgorges** [comment]
Thanks, there's already an [open issue](https://github.com/mikeemoo/ColorJizz-PHP/issues/10) for version tagging in the ColorJizz lib. I prefer not to fork it, but you're right.

**Comment by jpuck** [comment]
In deed I upvoted your issue, but @mikeemoo doesn't appear to be very active on Github.

You've made a fabulous package and it's been working perfectly for me. I'm quite surprised this useful utility has gone relatively undiscovered thus far. Really makes WCAG compliance a cinch with dynamic color schemes, thanks!

**Comment by jpuck** [comment]
I don't know how I missed it, but it appears as though he added a [1.0.0 release tag][1] back in November.

I commented on mikeemoo/ColorJizz-PHP#10 to point out that packagist hasn't picked up the tag.

I'll submit another PR with the vcs repository in `composer.json` that will allow faster resolution which will always see the available tags.

[1]:https://github.com/mikeemoo/ColorJizz-PHP/releases

**Comment by davidgorges** [comment]
Thank you @jpuck for your help! Very much appreciated.

**Comment by jpuck** [comment]
@davidgorges no problem. would you mind making a new release tag (e.g. v0.1.1) to pick up the stable changes in packagist? thanks

**Comment by jpuck** [comment]
@davidgorges hey, not sure if you saw my last comment on this issue, but I would like to require your package as a dependency inside a project without declaring minimum stability as dev, but I need a new release tag from you to do so. thanks

**Comment by davidgorges** [comment]
@jpuck thanks for reminding me. Just created v.0.1.1
